spring:
  datasource:
    url: jdbc:mysql://139.196.162.227:3306/db_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://172.20.0.112:3306/db_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: boss-bes-user
server:
  port: 8088
mybatis:
    configuration:
        map-underscore-to-camel-case: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 172.20.0.219:8761:luohui
  client:
    serviceUrl:
      defaultZone: http://172.20.0.219:8761/eureka/