spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://172.20.0.112:3306/db_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8088
mybatis:
    configuration:
        map-underscore-to-camel-case: true